version: "3"

tasks:
  devtools:
    cmds:
      - echo "***Starting Browser***"
      - go clean -modcache
      - $("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --remote-debugging-port=9222)
  auth:
    cmds:
      - echo "***Authenticating***"
      - go run ./test/authenticate.go -rod="show,trace" {{.CLI_ARGS}}
  cli:
    cmds:
      - echo "***Starting GoIq***"
      - go run . -rod="show,trace" {{.CLI_ARGS}}
  launcher:
    cmds:
      - echo "***Testing Launcher***"
      - go clean -modcache
      - go run ./test/test_launcher_lib.go -rod="show,trace" {{.CLI_ARGS}}
  scrape:
    cmds:
      - echo "***Testing Scrape***"
      - go clean -modcache
      - go run ./test/scrape.go -rod="show,trace" {{.CLI_ARGS}}
