version: "3"

tasks:
  start:
    cmds:
      - echo "***Starting Browser***"
      - go clean -modcache
      - echo "starting" && "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --remote-debugging-port=9222
      # remember to copy this value to pass it to login
  login:
    cmds:
      - echo "***Login to AWS***"
      - go clean -modcache
      - go run ./scripts/login.go -v -rod="show,trace" {{.CLI_ARGS}}
  dash:
    cmds:
      - echo "***Dashboard***"
      - go clean -modcache
      - go run ./scripts/dashboard.go -rod="show,trace" {{.CLI_ARGS}}
  cli:
    cmds:
      - echo "***Running CLI***"
      - go clean -modcache
      - go run ./scripts/cli.go {{.CLI_ARGS}}
