version: "3"

tasks:
  start:
    cmds:
      - echo "***Manual-Start***"
      - echo "starting" && "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --remote-debugging-port=9222
      # remember to copy this value to pass it to login
  login:
    cmds: 
      - echo "***Login***"
      - go clean -modcache 
      - go run ./scripts/login.go -v -rod="show,trace" {{.CLI_ARGS}}
  